export const TOGGLE_SNACKBAR = "TOGGLE_SNACKBAR";
export const TOGGLE_WATCHED_MOVIES = "TOGGLE_WATCHED_MOVIES";
export const TOGGLE_LOADING_MOVIES = "TOGGLE_LOADING_MOVIES";
export const SAVE_MOVIES = "SAVE_MOVIES";
export const SAVE_MOVIES_YEARS = "SAVE_MOVIES_YEARS";
export const ON_FILTERS_CHANGE = "ON_FILTERS_CHANGE";
export const ON_FREE_SEARCH_FILTER_CHANGE = "ON_FREE_SEARCH_FILTER_CHANGE";
export const ON_MOVIES_COUNTER_CHANGE = "ON_MOVIES_COUNTER_CHANGE";