export const TOGGLE_SNACKBAR = "TOGGLE_SNACKBAR";
export const TOGGLE_WATCHED_MOVIES = "TOGGLE_WATCHED_MOVIES";
export const TOGGLE_LOADING_MOVIES = "TOGGLE_LOADING_MOVIES";
export const SAVE_MOVIES = "SAVE_MOVIES";